apiVersion: apps/v1
kind: Deployment
metadata:
  name: wav2lip-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wav2lip-service
  template:
    metadata:
      labels:
        app: wav2lip-service
    spec:
      containers:
        - name: wav2lip-container
          image: felipediaz1/my_wav2lip_with_api:latest  # Imagen en Docker Hub
          ports:
            - containerPort: 8000
          imagePullPolicy: Always  # Asegura que siempre descargue la imagen más reciente
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: wav2lip-service
spec:
  type: NodePort
  selector:
    app: wav2lip-service
  ports:
    - protocol: TCP
      port: 8000  # Puerto en el cluster
      targetPort: 8000  # Puerto en el contenedor
      nodePort: 30002  # Puerto en el host de Minikube

